config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :questions do
      member do
        put 'upvote'
        put 'downvote'
      end
    resources :answers do
      member do
        put 'upvote'
        put 'downvote'
      end
    end
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :username, :body, presence: true

  default_scope { order(vote: :desc) }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :description, presence: true,
                          length: { minimum: 20 }

  validates :username, presence: true

  default_scope { order(vote: :desc) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def show
    @answer = Answer.find(params[:id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    render partial: 'answers/answer', locals: { answer: @answer }
    # redirect_to question_path(@question)
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
  end

  def update
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
    if @answer.update(answer_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    render nothing: true
    # redirect_to question_path(@answer.question)
  end

  def upvote
    @answer = Answer.find(params[:id])
    @answer.update(vote: @answer.vote+=1)
    render :json => @answer
    # redirect_to question_path(@answer.question)
  end

  def downvote
    @answer = Answer.find(params[:id])
    @answer.update(vote: @answer.vote-=1)
    render :json => @answer
    # redirect_to question_path(@answer.question)
  end


  private
  def answer_params
    params.require(:answer).permit(:username, :body, :vote)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include HTTParty
  def index
    @questions = Question.all
    @question = Question.new
    response = HTTParty.get('https://api.github.com/zen',:headers => {
      "Authorization" => 'token ' + ENV["AUTH_TOKEN"], "User-Agent" => "007"})
    if response.headers["x-ratelimit-remaining"].to_i > 1
      @response = response.parsed_response
    else
      @response = "If it hurts to breath, open a window."
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @blank_answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @questions = Question.all
    @question = Question.new(question_params)
    if @question.save
       render partial: 'questions/question'
    else
      render partial: '/questions/form'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    render :nothing => true
  end

  def upvote
    @question = Question.find(params[:id])
    @question.update(vote: (@question.vote + 1))
    render :json => @question
  end

  def downvote
    @question = Question.find(params[:id])
    @question.update(vote: @question.vote-=1)
    render :json => @question
  end

  private
  def question_params
    params.require(:question).permit(:title, :description, :username, :vote)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div class="answer" id="<%= answer.id %>">
  <p><strong>Username: </strong><%= answer.username %></p>
  <p><%= answer.body %></p>
  <p>Votes: <span class="vote"><%= answer.vote %></span></p>
  <ul>
    <li class="button upvote"><%= link_to 'Upvote', upvote_question_answer_path(answer.question, answer) %></li>
    <li class="button downvote"><%= link_to "Downvote", downvote_question_answer_path(answer.question, answer) %></li>
    <li class="button"><%= link_to 'Back to questions', questions_path %></li>
    <li class="button"><%= link_to 'Edit', edit_question_answer_path(answer.question, answer) %></li>
    <li class="button"><%= link_to 'Delete', question_answer_path(answer.question, answer), class: "delete-answer" %></li>
  </ul>
</div>

app/views/answers/_form.html.erb
<%= form_for([@question, @blank_answer]) do |f| %>
  <p>
    <%= f.text_field :username, placeholder: "username" %>
  </p>
  <p>
    <%= f.text_area :body, placeholder: "your answer" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/answers/edit.html.erb
<h1>DBC Overflow</h1>
<h3>Edit Answer</h3>

<%= render 'form' %>

<%= link_to 'Back to Questions', questions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DBC Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <%= link_to '/' do %>
  <h1>DBC Overflow</h1>
  <% end %>
  <p class="zen-quote">
    <%= @response %>
  </p>

    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<div class="question-form">
<%= form_for @question do |f| %>
<% if @question.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@question.errors.count, "error") %>
      prohibited this question from being saved
    </h2>
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.text_field :username , placeholder: "username"%>
  </p>
  <p>
    <%= f.text_field :title, class: "question-title" , placeholder: "what's your question"%>
  </p>
  <p>
    <%= f.text_area :description, class: "question-description", placeholder: "explain what isn't working"%>
  </p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/questions/_question.html.erb
<div class="question" id="<%= @question.id %>">
  <%= link_to question_path(@question) do %>
  <h3><%= @question.title %></h3>
  <% end %>
  <p><%= @question.description %></p>
  <p>Votes: <span class="vote"><%= @question.vote %></span></p>
  <p>Answers: <%= @question.answers.count %></p>
  <ul>
    <li class="button upvote"><%= link_to 'Upvote', upvote_question_path(@question) %></li>
    <li class="button downvote"><%= link_to "Downvote", downvote_question_path(@question) %></li>
    <li class="button"><%= link_to 'Edit', edit_question_path(@question)%></li>
    <li class="button"><%= link_to 'Delete', question_path(@question), class: "delete-question" %></li>
  </ul>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Back to Questions', questions_path %>

app/views/questions/index.html.erb
<div class="new_form">
<%= render 'form' %>
</div>

<h4>Questions</h4>
<div class="question-list">
  <% unless @questions.length == 0 %>
  <% @questions.each do |question| %>
  <div class="question" id="<%= question.id %>">
    <%= link_to question_path(question) do %>
    <h3><%= question.title %></h3>
    <% end %>
    <p><%= question.description %></p>
    <p>Votes: <span class="vote"><%= question.vote %></span></p>
    <p>Answers: <%= question.answers.count %></p>
    <ul>
      <li class="button upvote"><%= link_to 'Upvote', upvote_question_path(question) %></li>
      <li class="button downvote"><%= link_to "Downvote", downvote_question_path(question) %></li>
      <li class="button"><%= link_to 'Edit', edit_question_path(question)%></li>
      <li class="button"><%= link_to 'Delete', question_path(question), class: "delete-question" %></li>
    </ul>
  </div>
  <% end %>
  <% else %>
  <p>There are currently no questions. Please create one!</p>
  <% end %>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back to Questions', questions_path %>

app/views/questions/show.html.erb
<%= link_to questions_path(@question) do %>
<h3><%= @question.title %></h3>
<% end %>
<p><%= @question.description %></p>
<p>
  <strong>Username:</strong>
  <%= @question.username %>
</p>

<div class="answer-list">
<% unless @answers.length == 0 %>
<h4>Answers</h4>
<% @answers.each do |answer| %>
  <%= render 'answers/answer', answer: answer %>
<% end %>
<% end %>
</div>

<h2>Add an answer:</h2>
<%= render 'answers/form' %>

<li class="button"><%= link_to 'Back to Questions', questions_path %></li>
<li class="button"><%= link_to 'Edit', edit_question_path(@question) %></li>